package com.abhi.enums;

public enum ConfigProperties {
    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    RETRYFAILEDTESTS,
    RUNMODE,
    SENDRESULTTOELK,
    SELENIUMGRIDURL,
    BROWSER
}
